import React from 'react'

export const Preview = ({ content }: { content: string }) => {
  return (
    <div>{content}</div>
  )
}



//READ ME 
// I HAD SOME ISSUES WITH THE PREVIEW COMPONENT, SO I DECIDED TO CREATE A NEW COMPONENT JUST FOR THE PREVIEW CURRENTLY FINDING THE BEST PREVIEW LIBRARY TO FORMATTING THE CONTENT
// MAYBE I WILL BE USING THE MDX REMOTE LIBRARY TO RENDER THE CONTENT IN THE PREVIEW COMPONENT