import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/navigation/nav/nav";
import React from "react";
import localFont from "next/font/local"


const inter = localFont({
  src: "../fonts/interVF.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
});

const spaceGrotesk = localFont({
  src : "../fonts/SpaceGroteskVF.ttf",
  variable: "--font-SpaceGrotesk",
  weight: "300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${spaceGrotesk.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
